### ISSUE TITLE
Failed make - "No rule to make target 'conpubd.conf.def', needed by 'conpubd.conf'"

### ISSUE THREAD

**Issue by Marie673** [cefore/cefore#4]
An error occurred when executing the following:
```
 sudo apt-get install libssl-dev
sudo apt-get install automake
./configure
make
```

Error sentence
```
make[2]: *** No rule to make target 'conpubd.conf.def', needed by 'conpubd.conf'.  Stop.
make[2]: Leaving directory '/cefore/cefore/config'
Makefile:435: recipe for target 'all-recursive' failed
make[1]: Leaving directory '/cefore/cefore'
make[1]: *** [all-recursive] Error 1
Makefile:367: recipe for target 'all' failed
make: *** [all] Error 2
```

Similar errors occur in past [2021-hands-on](https://github.com/cefore/2021-hands-on/tree/main/practice-A) docker code.
How can I build without problems?

**Comment by cefore** [comment]
Thank you for your report. We will check it.

**Comment by cefore** [comment]
We fixed the typo of .gitignore to enable conpubd.conf.def.
Please retry to run 'make' command.

**Comment by Marie673** [comment]
I could build it.
Thank you for fix.
